### ISSUE TITLE
list.php can be accessed by everyone

### ISSUE THREAD

**Issue by milsen** [jelmervdl/kennissysteem#3]
list.php allows to download, analyse and remove all of the knowledge bases that were ever uploaded. It can be accessed by simply using .../list.php as the url. This may be by design but seems very unsafe to me. Moreover, there does not seem to be a link to list.php through index.php, which indicates to me that it should not be accessed by normal users. 

Granted, these knowledge bases probably do not contain any really important information, but e.g. earlier knowledge bases or knowledge bases by other assignment groups could be used to cheat on assignments in the coming years. Removing knowledge bases while others try to run them may also lead to weird errors.

**Comment by jelmervdl** [comment]
True, this is more an artefact from the previous form of this knowledge system and does not add anything anymore. I've removed it. Thanks for reporting it!
